s1='python內建函式可以對字串做字串轉換、字串搜尋、字串分割。'
s2='Hello World'
print(s1.find('字串'))
print(s1.find('字串',14,20))
print(s1.rfind('字串'))
print(s1.startswith('字串'))
print(s1.startswith('字串',13))
print(s1.index('字串',17))
print(s1.rindex('字串',0,20))
print(s1.count('字串'))
print(s1.split('、',1))
print(s1.split('、'))
print(s1.rsplit('、',1))
print('@'.join(s1.split('、')))
print(s1.replace('串','元'))
print(s2.capitalize())
print('hello world!'.title())
print('Hello\t World!'.expandtabs(10))
print('\tHello World!\n'.strip())
print(s2.rstrip('!'))
print(s2.lstrip('H'))
print(s2.upper())
print(s2.lower())
print(s2.title().swapcase())
print(max(s2))
print(min(min(s2)))
print(len(s2))
print(s2.center(18))
print(s2.rjust(16,'<'))
print(s2.ljust(16,'>'))
print(s2.zfill(16))
print('3M'.isalnum())
print('3M.isalpha()')
print('3M'.isdigit())
print('A or B'.isspace())
print('abc公司'.islower())
print('U-LIONS統一獅'.isupper())
print(s2.istitle())
